language: cpp
compiler:
  - gcc
cache: apt
before_install:
        - lsb_release -sc
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get clean
        - sudo apt-get update
install:
        - sudo apt-get install -f -y gcc-4.9 g++-4.9
script:
        - mkdir build && cd build
        - cmake ..
        - make -j2
