CList: nsSdD::CList< T > Class Template Reference
nsSdD::CList< T > Class Template Reference
#include <CList.hpp>
Classes
class CNodeIterator
Public Types
typedef CNodeIterator iterator
External iterator type.
typedef size_t size_type
External size type.
Public Member Functions
CList () noexcept
Initializes an empty list.
CList (size_type n, const T &val)
Creates a list of n elements with a value of val.
CList (size_type n)
Creates a list of n default-constructed elements.
CList (const CList &x)
Creates a copy of x.
CList (CList &&x)
Acquires the ressources of x.
template<typename InputIterator >
CList (InputIterator first, InputIterator last)
Creates a list by copying the elements in the range [first;last[.
CList (std::initializer_list< T > l)
Creates a list by copying the elements in the range [first;last[.
~CList () noexcept
Frees the allocated ressources.
CList< T > & operator= (const CList< T > &rhs)
Assigns the content of rhs to this Assigns the content of rhs to this.
CList< T > & operator= (CList< T > &&rhs)
Moves the content of rhs to this moves the content of rhs to this.
CList< T > & operator= (std::initializer_list< T > l)
Moves the content of rhs to this moves the content of rhs to this.
void unique ()
Remove duplicated consecutive elements.
void clear ()
Remove every elements in the list.
void remove (const T &val)
Remove every elements equal to val Remove every elements in the list that are equal to val.
void remove_if (std::function< bool(const T &)> predicate)
template<typename InputIterator >
iterator insert (iterator position, InputIterator first, InputIterator last)
Inserts a copy of every element in the range [first;last[ before position.
iterator insert (iterator position, const T &val)
Inserts a copy of val before position.
iterator insert (iterator position, size_type n, const T &val)
Inserts n copy of val before position.
void push_front (const T &val)
void push_back (const T &val)
iterator erase (iterator position)
Removes a node from the list, given an iterator position to it.
iterator erase (iterator first, iterator last)
Removes a range [first;last[ from the list.
void pop_front ()
Removes the first element of a list.
void pop_back ()
Removes the last element of a list.
bool empty () const noexcept
Checks whether a list is empty.
size_type size () const noexcept
Computes the size of a list.
CNodeIterator begin () const noexcept
Returns an iterator to the first element.
CNodeIterator end () const noexcept
Returns an iterator pointing after the last element.
size_type max_size () const noexcept
Returns the maximum number of elements that the list container can hold.
T & front () noexcept
Returns a reference to the first element of the list.
T & back () noexcept
Returns a reference to the last element of the list.
const T & front () const noexcept
Returns a reference to the first element of the list.
const T & back () const noexcept
Returns a reference to the last element of the list.
template<typename InputIterator >
void assign (InputIterator first, InputIterator last)
Assigns the content of the list by the elements in the [first; last[ range If the range is smaller than the current list size, the extra elements are erased. If the range is bigger than the current list size, the extra elements are copied.
void assign (size_type n, const T &val)
Assigns the content of the list by n copies of val.
void swap (CList &x)
Swaps the content of two lists.
void splice (iterator position, CList &x)
Move the content of a list before an element in another Moves the content of x before the element pointed by position.
void splice (iterator position, CList &x, iterator i)
Move an element from a list to another Moves the element at i from the list x and put it before position.
void splice (iterator position, CList &x, iterator first, iterator last)
Move a range of elements from a list to another Moves the elements in the range [first; last[ from the list x and put them before position.
void reverse ()
Reverse the order of elements in a list.
void resize (size_type n, const T &val=T())
Resize the container to n elements. If n > size(), the extra element are default constructed or copies of val else the list is truncated.
void merge (CList &x)
Merges two sorted lists into one If the lists aren't sorted this causes undefined behavior x is emptied after this operation.
void merge (CList &x, std::function< bool(const T &a, const T &b)> comp)
Merges two sorted lists into one If the lists aren't sorted this causes undefined behavior x is emptied after this operation.
void sort ()
Swaps the content of two lists. This sort is stable, it means consecutive equal elements keep their order.
template<typename... Args>
iterator emplace (iterator position, Args &&...args)
Construct and move an element before position.
template<typename... Args>
void emplace_front (Args &&...args)
Construct and move an element to the beginning of the list.
template<typename... Args>
void emplace_back (Args &&...args)
Construct and move an element to the end of the list.
Detailed Description
template<typename T>
class nsSdD::CList< T >
Circular list with memory being managed with a smart pointer
Definition at line 22 of file CList.hpp.
Member Typedef Documentation
template<typename T> typedef CNodeIterator nsSdD::CList< T >::iterator
External iterator type.
Definition at line 26 of file CList.hpp.
template<typename T> typedef size_t nsSdD::CList< T >::size_type
External size type.
Definition at line 30 of file CList.hpp.
Constructor & Destructor Documentation
template<typename T> nsSdD::CList< T >::CList () inline explicit noexcept
Initializes an empty list.
Definition at line 180 of file CList.hpp.
template<typename T> nsSdD::CList< T >::CList (size_type n, const T & val) inline
Creates a list of n elements with a value of val.
Parameters
n The number of elements to create
val A value to copy
Definition at line 190 of file CList.hpp.
template<typename T> nsSdD::CList< T >::CList (size_type n) inline explicit
Creates a list of n default-constructed elements.
Parameters
n The number of elements to create
Definition at line 199 of file CList.hpp.
References nsSdD::CList< T >::push_back().
template<typename T> nsSdD::CList< T >::CList (const CList< T > & x) inline explicit
Creates a copy of x.
Parameters
x The list to copy
Definition at line 209 of file CList.hpp.
References nsSdD::CList< T >::push_back().
template<typename T> nsSdD::CList< T >::CList (CList< T > && x) inline explicit
Acquires the ressources of x.
Parameters
x The list to get ressources from
Definition at line 219 of file CList.hpp.
References nsSdD::CList< T >::swap().
template<typename T> template<typename InputIterator > nsSdD::CList< T >::CList (InputIterator first, InputIterator last) inline
Creates a list by copying the elements in the range [first;last[.
Parameters
first An iterator on the first element to copy
last An iterator on the next node of the last node to copy
Definition at line 230 of file CList.hpp.
template<typename T> nsSdD::CList< T >::CList (std::initializer_list< T > l) inline
Creates a list by copying the elements in the range [first;last[.
Parameters
first An iterator on the first element to copy
last An iterator on the next node of the last node to copy
Definition at line 241 of file CList.hpp.
template<typename T> nsSdD::CList< T >::~CList () inline noexcept
Frees the allocated ressources.
Definition at line 245 of file CList.hpp.
Member Function Documentation
template<typename T> template<typename InputIterator > void nsSdD::CList< T >::assign (InputIterator first, InputIterator last) inline
Assigns the content of the list by the elements in the [first; last[ range If the range is smaller than the current list size, the extra elements are erased. If the range is bigger than the current list size, the extra elements are copied.
Complexity
Linear.
Iterator Validity
Every iterator are invalidated
Data races
Copied elements are accessed, container is modified, contained elements are modified
Parameters
first An iterator to the first element to assign
last An iterator following the last element to assign
Definition at line 560 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::erase(), and nsSdD::CList< T >::insert().
Referenced by nsSdD::CList< T >::assign(), and nsSdD::CList< T >::operator=().
template<typename T> void nsSdD::CList< T >::assign (size_type n, const T & val) inline
Assigns the content of the list by n copies of val.
Complexity
Linear.
Iterator Validity
Every iterator are invalidated
Data races
Copied elements are accessed, container is modified, contained elements are modified
Parameters
n Number of elements
val Value to copy
Definition at line 586 of file CList.hpp.
References nsSdD::CList< T >::assign(), nsSdD::CList< T >::begin(), and nsSdD::CList< T >::end().
template<typename T> T& nsSdD::CList< T >::back () inline noexcept
Returns a reference to the last element of the list.
Definition at line 525 of file CList.hpp.
References nsSdD::CList< T >::end().
template<typename T> const T& nsSdD::CList< T >::back () const inline noexcept
Returns a reference to the last element of the list.
Definition at line 539 of file CList.hpp.
References nsSdD::CList< T >::end().
template<typename T> CNodeIterator nsSdD::CList< T >::begin () const inline noexcept
Returns an iterator to the first element.
Returns
An iterator to the first element
Definition at line 498 of file CList.hpp.
Referenced by nsSdD::CList< T >::assign(), nsSdD::CList< T >::emplace_front(), nsSdD::CList< T >::front(), nsSdD::CList< T >::insert(), nsSdD::CList< T >::merge(), nsSdD::CList< T >::operator=(), nsSdD::CList< T >::pop_front(), nsSdD::CList< T >::push_front(), nsSdD::CList< T >::remove(), nsSdD::CList< T >::remove_if(), nsSdD::CList< T >::resize(), nsSdD::CList< T >::size(), nsSdD::CList< T >::sort(), nsSdD::CList< T >::splice(), and nsSdD::CList< T >::unique().
template<typename T> void nsSdD::CList< T >::clear () inline
Remove every elements in the list.
Definition at line 302 of file CList.hpp.
template<typename T> template<typename... Args> iterator nsSdD::CList< T >::emplace (iterator position, Args &&... args) inline
Construct and move an element before position.
Parameters
position Iterator to the position in the list
args... Constructor parameters
Definition at line 818 of file CList.hpp.
References nsSdD::CBaseNode::hook(), and nsSdD::CList< T >::CNodeIterator::m_CNodePtr.
Referenced by nsSdD::CList< T >::emplace_back(), and nsSdD::CList< T >::emplace_front().
template<typename T> template<typename... Args> void nsSdD::CList< T >::emplace_back (Args &&... args) inline
Construct and move an element to the end of the list.
Parameters
args... Constructor parameters
Definition at line 840 of file CList.hpp.
References nsSdD::CList< T >::emplace(), and nsSdD::CList< T >::end().
template<typename T> template<typename... Args> void nsSdD::CList< T >::emplace_front (Args &&... args) inline
Construct and move an element to the beginning of the list.
Parameters
args... Constructor parameters
Definition at line 830 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::emplace().
template<typename T> bool nsSdD::CList< T >::empty () const inline noexcept
Checks whether a list is empty.
Returns
True if the list is empty
Definition at line 480 of file CList.hpp.
Referenced by nsSdD::CList< T >::reverse(), nsSdD::CList< T >::sort(), TEST(), and nsSdD::CList< T >::unique().
template<typename T> CNodeIterator nsSdD::CList< T >::end () const inline noexcept
Returns an iterator pointing after the last element.
Returns
An iterator pointing after the last element.
Definition at line 507 of file CList.hpp.
Referenced by nsSdD::CList< T >::assign(), nsSdD::CList< T >::back(), nsSdD::CList< T >::emplace_back(), nsSdD::CList< T >::merge(), nsSdD::CList< T >::operator=(), nsSdD::CList< T >::pop_back(), nsSdD::CList< T >::push_back(), nsSdD::CList< T >::remove(), nsSdD::CList< T >::remove_if(), nsSdD::CList< T >::resize(), nsSdD::CList< T >::size(), nsSdD::CList< T >::splice(), and nsSdD::CList< T >::unique().
template<typename T> iterator nsSdD::CList< T >::erase (iterator position) inline
Removes a node from the list, given an iterator position to it.
Complexity
Constant.
Iterator Validity
Every iterator in the removed range are invalidated
Data races
Container is modified, removed elements are modified, acessing and iterating through the others elements is safe
Parameters
position An iterator pointing the element to remove
Returns
An iterator to the element following the one deleted
Definition at line 436 of file CList.hpp.
References nsSdD::CList< T >::CNodeIterator::m_CNodePtr, nsSdD::CBaseNode::m_next, and nsSdD::CBaseNode::unhook().
Referenced by nsSdD::CList< T >::assign(), nsSdD::CList< T >::erase(), nsSdD::CList< T >::pop_back(), nsSdD::CList< T >::pop_front(), nsSdD::CList< T >::remove(), nsSdD::CList< T >::remove_if(), nsSdD::CList< T >::resize(), and nsSdD::CList< T >::unique().
template<typename T> iterator nsSdD::CList< T >::erase (iterator first, iterator last) inline
Removes a range [first;last[ from the list.
Complexity
Linear.
Iterator Validity
Every iterator in the removed range are invalidated
Data races
Container is modified, removed elements are modified, acessing and iterating through the others elements is safe
Parameters
first An iterator to the first element to remove
last An iterator following the last element to remove
Returns
An iterator to the element following the last deleted element
Definition at line 456 of file CList.hpp.
References nsSdD::CList< T >::erase().
template<typename T> T& nsSdD::CList< T >::front () inline noexcept
Returns a reference to the first element of the list.
Definition at line 519 of file CList.hpp.
References nsSdD::CList< T >::begin().
template<typename T> const T& nsSdD::CList< T >::front () const inline noexcept
Returns a reference to the first element of the list.
Definition at line 533 of file CList.hpp.
References nsSdD::CList< T >::begin().
template<typename T> template<typename InputIterator > iterator nsSdD::CList< T >::insert (iterator position, InputIterator first, InputIterator last) inline
Inserts a copy of every element in the range [first;last[ before position.
Complexity
Linear.
Iterator Validity
Every iterators are still valid
Data races
Container is modified, no contained element are modified, acessing and iterating through the others elements is safe, except through ranges including position
Parameters
position Iterator on the element the range is copied before.
first Iterator on the first element to be copied
last Iterator on the last element of the range
Returns
An iterator to the first added element
Definition at line 353 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::splice().
Referenced by nsSdD::CList< T >::assign(), nsSdD::CList< T >::push_back(), nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::resize().
template<typename T> iterator nsSdD::CList< T >::insert (iterator position, const T & val) inline
Inserts a copy of val before position.
Complexity
Constant.
Iterator Validity
Every iterators are still valid
Data races
Container is modified, no contained element are modified, acessing and iterating through the others elements is safe, except through ranges including position
Parameters
position Iterator on the element val is copied before.
val The value to copy.
Returns
An iterator to the first added element
Definition at line 374 of file CList.hpp.
References nsSdD::CBaseNode::hook(), and nsSdD::CList< T >::CNodeIterator::m_CNodePtr.
template<typename T> iterator nsSdD::CList< T >::insert (iterator position, size_type n, const T & val) inline
Inserts n copy of val before position.
Complexity
Linear.
Iterator Validity
Every iterators are still valid
Data races
Container is modified, no contained element are modified, acessing and iterating through the others elements is safe, except through ranges including position
Parameters
position Iterator on the element val is copied before.
n The number of copies to insert before position.
val The value to copy.
Returns
An iterator to the first added element
Definition at line 395 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::splice().
template<typename T> size_type nsSdD::CList< T >::max_size () const inline noexcept
Returns the maximum number of elements that the list container can hold.
Definition at line 513 of file CList.hpp.
template<typename T> void nsSdD::CList< T >::merge (CList< T > & x) inline
Merges two sorted lists into one If the lists aren't sorted this causes undefined behavior x is emptied after this operation.
Complexity
Linear.
Iterator Validity
All iterator remain valid
Data races
Both container are accessed, contained elements are accessed but never modified. Iterating through the list concurrently is not safe
Parameters
x The list to merge into
Definition at line 720 of file CList.hpp.
Referenced by nsSdD::CList< T >::sort().
template<typename T> void nsSdD::CList< T >::merge (CList< T > & x, std::function< bool(const T &a, const T &b)> comp) inline
Merges two sorted lists into one If the lists aren't sorted this causes undefined behavior x is emptied after this operation.
Complexity
Linear.
Iterator Validity
All iterator remain valid
Data races
Both container are accessed, contained elements are accessed but never modified. Iterating through the list concurrently is not safe
Parameters
x The list to merge into
comp Binary predicate that evaluates to true if its first argument is considered strictly inferior to its second
Definition at line 741 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::end().
template<typename T> CList<T>& nsSdD::CList< T >::operator= (const CList< T > & rhs) inline
Assigns the content of rhs to this Assigns the content of rhs to this.
Parameters
rhs The Right Hand Side of the expression
Definition at line 255 of file CList.hpp.
References nsSdD::CList< T >::assign(), nsSdD::CList< T >::begin(), and nsSdD::CList< T >::end().
template<typename T> CList<T>& nsSdD::CList< T >::operator= (CList< T > && rhs) inline
Moves the content of rhs to this moves the content of rhs to this.
Parameters
rhs The Right Hand Side of the expression
Definition at line 267 of file CList.hpp.
References nsSdD::CList< T >::swap().
template<typename T> CList<T>& nsSdD::CList< T >::operator= (std::initializer_list< T > l) inline
Moves the content of rhs to this moves the content of rhs to this.
Parameters
rhs The Right Hand Side of the expression
Definition at line 278 of file CList.hpp.
References nsSdD::CList< T >::assign().
template<typename T> void nsSdD::CList< T >::pop_back () inline
Removes the last element of a list.
Definition at line 470 of file CList.hpp.
References nsSdD::CList< T >::end(), and nsSdD::CList< T >::erase().
template<typename T> void nsSdD::CList< T >::pop_front () inline
Removes the first element of a list.
Definition at line 464 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::erase().
template<typename T> void nsSdD::CList< T >::push_back (const T & val) inline
Copies an element and put it at the end of the list
Parameters
val The value to copie
Definition at line 420 of file CList.hpp.
References nsSdD::CList< T >::end(), and nsSdD::CList< T >::insert().
Referenced by nsSdD::CList< T >::CList(), and TEST().
template<typename T> void nsSdD::CList< T >::push_front (const T & val) inline
Copies an element and put it at the beginning of the list
Parameters
val The value to copie
Definition at line 411 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::insert().
template<typename T> void nsSdD::CList< T >::remove (const T & val) inline
Remove every elements equal to val Remove every elements in the list that are equal to val.
Complexity
Linear.
Iterator Validity
Every iterators are still valid, except those on removed elements
Data races
Container is modified, removed elements are modified, iterating on removed elements is not safe.
Parameters
val Value to compare
Definition at line 319 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), and nsSdD::CList< T >::erase().
template<typename T> void nsSdD::CList< T >::remove_if (std::function< bool(const T &)> predicate) inline
Remove every elements in the list if the predicates evaluates to true
Parameters
predicate Unary predicates evaluating to true for elements to be removed
Definition at line 330 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), and nsSdD::CList< T >::erase().
template<typename T> void nsSdD::CList< T >::resize (size_type n, const T & val = T()) inline
Resize the container to n elements. If n > size(), the extra element are default constructed or copies of val else the list is truncated.
Complexity
Linear.
Iterator Validity
All iterator remain valid, except the ones on the removed elements
Data races
Both container are accessed, removed elements are accessed, iterating throught the others is safe. Iterating through the list concurrently is not safe
Parameters
n The new size of the list
val Element to copy when creating elements in the container
Definition at line 696 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::erase(), and nsSdD::CList< T >::insert().
template<typename T> void nsSdD::CList< T >::reverse () inline
Reverse the order of elements in a list.
Complexity
Linear.
Iterator Validity
All iterator remain valid
Data races
Both container are accessed, accessing and modifying elements is safe, iterating through is not safe.
Definition at line 676 of file CList.hpp.
References nsSdD::CList< T >::empty().
template<typename T> size_type nsSdD::CList< T >::size () const inline noexcept
Computes the size of a list.
Returns
The size of the list
Definition at line 489 of file CList.hpp.
References nsSdD::CList< T >::begin(), and nsSdD::CList< T >::end().
template<typename T> void nsSdD::CList< T >::sort () inline
Swaps the content of two lists. This sort is stable, it means consecutive equal elements keep their order.
Complexity
Approximately N log N.
Iterator Validity
All iterator remain valid
Data races
Both container are accessed, contained elements are accessed but never modified. Iterating through the list concurrently is not safe
Definition at line 776 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::empty(), nsSdD::CList< T >::merge(), nsSdD::CList< T >::splice(), and nsSdD::CList< T >::swap().
template<typename T> void nsSdD::CList< T >::splice (iterator position, CList< T > & x) inline
Move the content of a list before an element in another Moves the content of x before the element pointed by position.
Complexity
Constant.
Iterator Validity
All iterator remain valid, the iterators on the transfered element are now iterating in the other list
Data races
Both container are accessed, accessing and modifying elements is safe, iterating through is not safe.
Parameters
position Iterator on the element to move before
x List to move before position
Definition at line 619 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::CNodeIterator::m_CNodePtr, and nsSdD::CBaseNode::transfer().
Referenced by nsSdD::CList< T >::insert(), and nsSdD::CList< T >::sort().
template<typename T> void nsSdD::CList< T >::splice (iterator position, CList< T > & x, iterator i) inline
Move an element from a list to another Moves the element at i from the list x and put it before position.
Complexity
Constant.
Iterator Validity
All iterator remain valid, the iterators on the transfered element are now iterating in the other list
Data races
Both container are accessed, accessing and modifying elements is safe, iterating through is not safe.
Parameters
position Iterator on the element to move before
x List to move an element from
i Iterator on the element to move
Definition at line 638 of file CList.hpp.
References nsSdD::CList< T >::CNodeIterator::m_CNodePtr, and nsSdD::CBaseNode::transfer().
template<typename T> void nsSdD::CList< T >::splice (iterator position, CList< T > & x, iterator first, iterator last) inline
Move a range of elements from a list to another Moves the elements in the range [first; last[ from the list x and put them before position.
Complexity
Constant.
Iterator Validity
All iterator remain valid, the iterators on x are now iterating in the other list
Data races
Both container are accessed, accessing and modifying elements is safe, iterating through is not safe.
Parameters
position Iterator on the element to move before
x List to move an element from
first Iterator on the first element of the range
last Iterator on the last element of the range
Definition at line 661 of file CList.hpp.
References nsSdD::CList< T >::CNodeIterator::m_CNodePtr, and nsSdD::CBaseNode::transfer().
template<typename T> void nsSdD::CList< T >::swap (CList< T > & x) inline
Swaps the content of two lists.
Complexity
Constant.
Iterator Validity
All iterator remain valid, but instead refers to elements in the other list
Data races
Both container are accessed, none of the contained elements are.
Parameters
x A list to swap
Definition at line 602 of file CList.hpp.
References nsSdD::CBaseNode::swap().
Referenced by nsSdD::CList< T >::CList(), nsSdD::CList< T >::operator=(), nsSdD::CList< T >::sort(), and nsSdD::swap().
template<typename T> void nsSdD::CList< T >::unique () inline
Remove duplicated consecutive elements.
Definition at line 285 of file CList.hpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::empty(), nsSdD::CList< T >::end(), and nsSdD::CList< T >::erase().