CList: nsSdD::CBaseNode Class Reference
nsSdD::CBaseNode Class Reference
Doubly-linked node in a circular list.
#include <CBaseNode.hpp>
Public Member Functions
void hook (pointer elem)
Places this node before elem.
pointer GetSuivant ()
Returns a pointer to the next node. This is unused and only there to maintain comptability with eventual tests.
void unhook ()
Removes a node from its list. Its ressources aren't freed.
void transfer (CBaseNode *first, CBaseNode *last)
Moves a range [first;last[ of nodes and put it before "this" If last is the node that called this method, the list remains untouched.
void reverse ()
Reverse the order of the elements in a list.
Static Public Member Functions
static void swap (CBaseNode &x, CBaseNode &y)
Swaps two nodes, that could be in differents lists.
Public Attributes
pointer m_prev = nullptr
Pointer to the previous node.
pointer m_next = nullptr
Pointer to the next node.
Detailed Description
Doubly-linked node in a circular list.
Definition at line 11 of file CBaseNode.hpp.
Member Function Documentation
pointer nsSdD::CBaseNode::GetSuivant () inline
Returns a pointer to the next node. This is unused and only there to maintain comptability with eventual tests.
Returns
A pointer to the next node
Definition at line 40 of file CBaseNode.hpp.
References m_next.
void nsSdD::CBaseNode::hook (pointer elem) inline
Places this node before elem.
Parameters
elem The node to put "this" before.
Definition at line 26 of file CBaseNode.hpp.
References m_next, and m_prev.
Referenced by nsSdD::CList< T >::emplace(), and nsSdD::CList< T >::insert().
void nsSdD::CBaseNode::reverse () inline
Reverse the order of the elements in a list.
Definition at line 82 of file CBaseNode.hpp.
References m_next, m_prev, and nsSdD::swap().
static void nsSdD::CBaseNode::swap (CBaseNode & x, CBaseNode & y) inline static
Swaps two nodes, that could be in differents lists.
Parameters
x A node to swap
y Another node to swap
Definition at line 97 of file CBaseNode.hpp.
References m_next, m_prev, and nsSdD::swap().
Referenced by nsSdD::CList< T >::swap().
void nsSdD::CBaseNode::transfer (CBaseNode * first, CBaseNode * last) inline
Moves a range [first;last[ of nodes and put it before "this" If last is the node that called this method, the list remains untouched.
Parameters
first Pointer to the first element in the range
last Pointer to the last element in the range
Definition at line 67 of file CBaseNode.hpp.
References m_next, and m_prev.
Referenced by nsSdD::CList< T >::splice().
void nsSdD::CBaseNode::unhook () inline
Removes a node from its list. Its ressources aren't freed.
Definition at line 53 of file CBaseNode.hpp.
References m_next, and m_prev.
Referenced by nsSdD::CList< T >::erase().
Member Data Documentation
pointer nsSdD::CBaseNode::m_next = nullptr
Pointer to the next node.
Definition at line 20 of file CBaseNode.hpp.
Referenced by nsSdD::CList< T >::erase(), GetSuivant(), hook(), nsSdD::CList< T >::CNodeIterator::operator++(), reverse(), swap(), transfer(), and unhook().
pointer nsSdD::CBaseNode::m_prev = nullptr
Pointer to the previous node.
Definition at line 18 of file CBaseNode.hpp.
Referenced by hook(), nsSdD::CList< T >::CNodeIterator::operator--(), reverse(), swap(), transfer(), and unhook().