CList: main.cpp File Reference
test/main.cpp File Reference
#include <CList.hpp>
#include <list>
#include <sstream>
#include <test_traits.hpp>
#include <test_framework.hpp>
#include <test_classes.hpp>
Functions
TEST (insert)
TEST (sort)
TEST (erase)
TEST (unique)
TEST (merge)
TEST (test)
TEST (pop_back)
TEST (pop_front)
TEST (push_back)
TEST (push_front)
TEST (front)
TEST (back)
TEST (clear)
TEST (remove)
TEST (remove_if)
TEST (reverse)
TEST (size)
int main ()
Function Documentation
int main ()
Definition at line 405 of file test/main.cpp.
TEST (insert)
Definition at line 16 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::insert(), and IZI_ASSERT.
TEST (sort)
Definition at line 49 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::push_back(), and nsSdD::CList< T >::sort().
TEST (erase)
Definition at line 70 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::erase(), IZI_ASSERT, and nsSdD::CList< T >::push_back().
TEST (unique)
Definition at line 97 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::push_back(), and nsSdD::CList< T >::unique().
TEST (merge)
Definition at line 118 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::empty(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::merge(), nsSdD::CList< T >::push_back(), and nsSdD::CList< T >::sort().
TEST (test)
Definition at line 154 of file test/main.cpp.
References IZI_ASSERT.
TEST (pop_back)
Definition at line 159 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::pop_back(), and nsSdD::CList< T >::push_back().
TEST (pop_front)
Definition at line 186 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::pop_front(), and nsSdD::CList< T >::push_front().
TEST (push_back)
Definition at line 213 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, and nsSdD::CList< T >::push_back().
TEST (push_front)
Definition at line 240 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, and nsSdD::CList< T >::push_front().
TEST (front)
Definition at line 268 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), nsSdD::CList< T >::front(), IZI_ASSERT, and nsSdD::CList< T >::push_front().
TEST (back)
Definition at line 289 of file test/main.cpp.
References nsSdD::CList< T >::back(), nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, and nsSdD::CList< T >::push_back().
TEST (clear)
Definition at line 310 of file test/main.cpp.
References nsSdD::CList< T >::clear(), IZI_ASSERT, nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::size().
TEST (remove)
Definition at line 325 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::remove().
TEST (remove_if)
Definition at line 346 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::remove_if().
TEST (reverse)
Definition at line 367 of file test/main.cpp.
References nsSdD::CList< T >::begin(), nsSdD::CList< T >::end(), IZI_ASSERT, nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::reverse().
TEST (size)
Definition at line 388 of file test/main.cpp.
References IZI_ASSERT, nsSdD::CList< T >::push_front(), and nsSdD::CList< T >::size().